version: '3.7'

services:
  django_gunicorn:
    container_name: azad_django
    volumes:
      - static:/static  
    env_file:
      - ./.env
    build:
      context: .
    ports:
      - "9000:9000"
  nginx:
    build: ./nginx
    volumes:
      - static:/app/static
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn

volumes:
  static:
